### ISSUE TITLE
Errors from Racecar::Cli#initialize are swallowed

### ISSUE THREAD

**Issue by rvedotrc** [zendesk/racecar#106]
For example if a "--require"d file raises an exception.

```
19451-revans:racecar revans$ git rev-parse HEAD
236a8872c406e4707a1c876d4a55d6ca61494f63

19451-revans:racecar revans$ > lib/foo.rb
19451-revans:racecar revans$ ruby -I lib ./exe/racecar --require foo bar
=> Starting Racecar consumer bar...
=> Crashed: NameError: wrong constant name bar
/Users/revans/git/github.com/rvedotrc/github-mirror/var/checkout/full_name/zendesk/racecar/lib/racecar/cli.rb:33:in `const_get'
/Users/revans/git/github.com/rvedotrc/github-mirror/var/checkout/full_name/zendesk/racecar/lib/racecar/cli.rb:33:in `run'
/Users/revans/git/github.com/rvedotrc/github-mirror/var/checkout/full_name/zendesk/racecar/lib/racecar/cli.rb:10:in `main'
./exe/racecar:9:in `<main>'

19451-revans:racecar revans$ echo 'raise' > lib/foo.rb
19451-revans:racecar revans$ ruby -I lib ./exe/racecar --require foo bar
19451-revans:racecar revans$ echo $?
1
```

**Comment by rvedotrc** [comment]
The swallowing is presumably being done by the top-level "begin / rescue / exit 1" logic in exe/racecar. However as previously discussed it's not apparent why that top-level rescue logic is even there in the first place.
