### ISSUE TITLE
Exception: Unsupported compression type

### ISSUE THREAD

**Issue by dasch** [zendesk/racecar#122]
Got this when restarting Kafka in local dev:

```
Crashed: Rdkafka::RdkafkaError: Unsupported compression type (unsupported_compression_type)
/bundle/gems/rdkafka-0.6.0/lib/rdkafka/consumer.rb:355:in `poll'
/bundle/gems/racecar-2.0.0.alpha1/lib/racecar/consumer_set.rb:16:in `poll'
/bundle/gems/racecar-2.0.0.alpha1/lib/racecar/runner.rb:69:in `block (2 levels) in run'
/bundle/gems/activesupport-5.1.6.2/lib/active_support/notifications.rb:168:in `instrument'
/bundle/gems/racecar-2.0.0.alpha1/lib/racecar/runner.rb:61:in `block in run'
/bundle/gems/racecar-2.0.0.alpha1/lib/racecar/runner.rb:58:in `loop'
/bundle/gems/racecar-2.0.0.alpha1/lib/racecar/runner.rb:58:in `run'
/bundle/gems/racecar-2.0.0.alpha1/lib/racecar.rb:50:in `run'
/bundle/gems/racecar-2.0.0.alpha1/lib/racecar/cli.rb:63:in `run'
/bundle/gems/racecar-2.0.0.alpha1/lib/racecar/cli.rb:10:in `main'
/bundle/gems/racecar-2.0.0.alpha1/exe/racecar:7:in `<top (required)>'
bin/racecar:17:in `load'
bin/racecar:17:in `<main>'
```

/cc @JHK @breunigs

**Comment by JHK** [comment]
Good one, we set it to `lz4` everywhere. I'll have a look

**Comment by JHK** [comment]
I wonder how compression comes into play on the consumer side. According to https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md the compression parameters can only be set for producers.

**Comment by dasch** [comment]
🤷‍♂ 

I'm not even sure why this happened – it was during broker shutdown. Could be an incorrect error message.

**Comment by breunigs** [comment]
I’m on mobile right now, but generally speaking printing the error code might be helpful. Depending on the versions in use there might be a disagreement on what an error code means, see e.g. https://github.com/edenhill/librdkafka/issues/2245

**Comment by breunigs** [comment]
I don't know how to reproduce this.

Using Kafka 2.3.0 / Zookeeper 3.4.13 from https://github.com/wurstmeister/kafka-docker in single broker mode (`docker-compose-single-broker.yml` with `KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1`) I manage to get a
```
Rdkafka::RdkafkaError: Local: Broker transport failure (transport)
```
with essentially the same stack trace when
1. `docker-compose -f docker-compose-single-broker.yml up`
2. start racecar consumer
3. `CTRL+C` docker compose
This doesn't always work for some reason (timing?), but the error message seems decent enough. The transport failure one is also years old, so it's unlikely I'm hitting a code path with changed/unreleased/mismatched error codes from Kafka and librdkafka.

Can you provide more details about your local setup? Generally speaking I'm hesitant to add re-connect in these scenarios because resetting librdkafka's internal offset state is not trivial.

**Comment by dasch** [comment]
I can try to see if I can hit the condition again.

However – the consumers are supposed to be resilient to temporary cluster failures. I think we need _some_ kind of automatic retries.

**Comment by JHK** [comment]
I think that _let it crash_ is a reasonable strategy for unknown and unpredictable errors. It is advisable anyway to have a supervising process that does restarts (with exponential back-off) and alerting.

When there is a possibility to reproduce the condition, then it makes sense to handle it here. Probably catch/retry this specific exception + error code around `poll` in the `ConsumerSet`. Otherwise the situation could get worse, as @breunigs described with unknowns in the internal state of rdkafka.

I think that we should not introduce a generic mechanism for automatic retries.

**Comment by dasch** [comment]
Is `Broker transport failure` not a temporary error condition? Or does that indicate a configuration error?

**Comment by breunigs** [comment]
Unfortunately it can be both: https://github.com/edenhill/librdkafka/wiki/FAQ#why-am-i-seeing-receive-failed-disconnected (via https://github.com/edenhill/librdkafka/issues/1664). However, the client misconfiguration is only happening when librdkafka and broker version are an incompatible match, which seems much less likely than random TCP hiccup.

So, something like this around polling?
```ruby
begin
  # …
rescue => e
  retries = (retries || 0) + 1
  raise if e.error_code = 123456 || retries > MAX_RETRIES
  sleep 2 ** retries
  retry
end
```

Please note that we were generally letting Kubernetes handle these restarts for us, so we might have missed some error cases if they didn't occur regularly enough.
