### ISSUE TITLE
undefined method `instrument` for nil:NilClass when running racecar without Rails

### ISSUE THREAD

**Issue by sweetat-xfers** [zendesk/racecar#171]
I wrote a simple test case with the following code:
```
require "spec_helper"
require_relative "../pre_trade_checks_consumer"

RSpec.describe PreTradeChecksConsumer do
  it "queues txn in txn.pretrades.ok queue when amt < 100.0" do
    message = double("message", 
            value: Hash[
              "id" => 1,
              "amt" => 99.0,
              ].to_json,
            key: 123, 
            )

    consumer = PreTradeChecksConsumer.new
    consumer.process(message)

    messages = kafka.messages_in("txn.pretrade.ok")
    expect(messages.map(&:payload)).to exists
  end
end
```

Running this with 
```
RACECAR_BROKERS=broker1:9091 bundle exec rspec spec/pre_trade_checks_consumer_test.rb
```

Shows me  the following error
```
  1) PreTradeChecksConsumer queues txn in txn.pretrades.ok queue when amt < 100.0
     Failure/Error: consumer.process(message)
       #<Double "message"> received unexpected message :topic with (no args)
     # ./pre_trade_checks_consumer.rb:32:in `rescue in process'
     # ./pre_trade_checks_consumer.rb:7:in `process'
     # ./spec/pre_trade_checks_consumer_test.rb:15:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `instrument' for nil:NilClass
     #   ./pre_trade_checks_consumer.rb:14:in `process'
```

Is this because racecar tries to instrument using ActiveSupport?  If we do not have ActiveSupport, can I just leave things be?

**Comment by dasch** [comment]
You need to call `configure` on the consumer instance, I think.

**Comment by dasch** [comment]
https://github.com/zendesk/racecar/blob/163497d3e7ac3f71a0af7372501db9cd9c6f3568/lib/racecar/consumer.rb#L33
