### ISSUE TITLE
NoMethodError: undefined method `assignment' for nil:NilClass

### ISSUE THREAD

**Issue by atrzaska** [zendesk/racecar#230]
Hello! We're using racecar 2 in our setup. It throws this error from time to time:

```
NoMethodError: undefined method `assignment' for nil:NilClass
  from racecar (2.2.0) lib/racecar/consumer_set.rb:169:in `block in find_consumer_by'
  from racecar (2.2.0) lib/racecar/consumer_set.rb:76:in `block in each_subscribed'
  from racecar (2.2.0) lib/racecar/consumer_set.rb:76:in `each'
  from racecar (2.2.0) lib/racecar/consumer_set.rb:76:in `each_subscribed'
  from racecar (2.2.0) lib/racecar/consumer_set.rb:168:in `find_consumer_by'
  from racecar (2.2.0) lib/racecar/consumer_set.rb:95:in `resume'
  from racecar (2.2.0) lib/racecar/runner.rb:250:in `block (2 levels) in resume_paused_partitions'
  from racecar (2.2.0) lib/racecar/runner.rb:239:in `each'
  from racecar (2.2.0) lib/racecar/runner.rb:239:in `block in resume_paused_partitions'
  from racecar (2.2.0) lib/racecar/runner.rb:238:in `each'
  from racecar (2.2.0) lib/racecar/runner.rb:238:in `resume_paused_partitions'
  from racecar (2.2.0) lib/racecar/runner.rb:66:in `block in run'
  from racecar (2.2.0) lib/racecar/runner.rb:64:in `loop'
  from racecar (2.2.0) lib/racecar/runner.rb:64:in `run'
  from racecar (2.2.0) lib/racecar.rb:54:in `run'
  from racecar (2.2.0) lib/racecar/cli.rb:63:in `run'
  from racecar (2.2.0) lib/racecar/cli.rb:13:in `main'
  from racecar (2.2.0) exe/racecar:9:in `start'
  from racecar (2.2.0) exe/racecar:44:in `<top (required)>'
  from gems/bin/racecar:23:in `load'
  from gems/bin/racecar:23:in `<top (required)>'
  from bundler/cli/exec.rb:63:in `load'
  from bundler/cli/exec.rb:63:in `kernel_load'
  from bundler/cli/exec.rb:28:in `run'
  from bundler/cli.rb:494:in `exec'
  from bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  from bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  from bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  from bundler/cli.rb:30:in `dispatch'
  from bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  from bundler/cli.rb:24:in `start'
  from bundler (2.2.7) exe/bundle:49:in `block in <top (required)>'
  from bundler/friendly_errors.rb:130:in `with_friendly_errors'
  from bundler (2.2.7) exe/bundle:37:in `<top (required)>'
  from /opt/ruby-2.7.2/bin/bundle:23:in `load'
  from /opt/ruby-2.7.2/bin/bundle:23:in `<main>'
```

https://github.com/zendesk/racecar/blob/master/lib/racecar/consumer_set.rb#L169

Looks like it iterates over the consumers when a consumer is getting reset.

This issue does not happen a lot. So far it occured a few times.

**Comment by deepredsky** [comment]
Thanks for reporting the bug. Can you try to check if newer version of racecar still has this issue and reopen accordingly.
