### ISSUE TITLE
Consumer thread crashed

### ISSUE THREAD

**Issue by surfdog** [zendesk/racecar#41]
I have 3 different environments.   In 2 out of 3, starting a racecar consumer works fine.  In the third, I get the following error:

```
racecar UserEventConsumer
=> Starting Racecar consumer UserEventConsumer...
=> Detected Rails, booting application...
=> Wrooooom!
=> Ctrl-C to shutdown consumer
I, [2017-11-15T13:25:23.172617 #68337]  INFO -- : New topics added to target list: playground_2
I, [2017-11-15T13:25:23.172819 #68337]  INFO -- : Fetching cluster metadata from kafka://development-magicbus1.cloudith.com:9092
D, [2017-11-15T13:25:23.173106 #68337] DEBUG -- : Opening connection to development-magicbus1.cloudith.com:9092 with client id tms...
D, [2017-11-15T13:25:23.263129 #68337] DEBUG -- : Sending request 1 to development-magicbus1.cloudith.com:9092
D, [2017-11-15T13:25:23.263456 #68337] DEBUG -- : Waiting for response 1 from development-magicbus1.cloudith.com:9092
D, [2017-11-15T13:25:23.298736 #68337] DEBUG -- : Received response 1 from development-magicbus1.cloudith.com:9092
I, [2017-11-15T13:25:23.299062 #68337]  INFO -- : Discovered cluster metadata; nodes: development-magicbus2.cloudith.com:9092 (node_id=2), development-magicbus5.cloudith.com:9092 (node_id=5), development-magicbus4.cloudith.com:9092 (node_id=4), development-magicbus1.cloudith.com:9092 (node_id=1), development-magicbus3.cloudith.com:9092 (node_id=3)
D, [2017-11-15T13:25:23.299143 #68337] DEBUG -- : Closing socket to development-magicbus1.cloudith.com:9092
I, [2017-11-15T13:25:23.299296 #68337]  INFO -- : Joining group `test`
D, [2017-11-15T13:25:23.299390 #68337] DEBUG -- : Getting group coordinator for `test`
D, [2017-11-15T13:25:23.299592 #68337] DEBUG -- : Opening connection to development-magicbus2.cloudith.com:9092 with client id tms...
D, [2017-11-15T13:25:23.377238 #68337] DEBUG -- : Sending request 1 to development-magicbus2.cloudith.com:9092
D, [2017-11-15T13:25:23.377368 #68337] DEBUG -- : Waiting for response 1 from development-magicbus2.cloudith.com:9092
D, [2017-11-15T13:25:23.413285 #68337] DEBUG -- : Received response 1 from development-magicbus2.cloudith.com:9092
I, [2017-11-15T13:25:23.413531 #68337]  INFO -- : Leaving group `test`
D, [2017-11-15T13:25:23.413575 #68337] DEBUG -- : Getting group coordinator for `test`
D, [2017-11-15T13:25:23.413716 #68337] DEBUG -- : Sending request 2 to development-magicbus2.cloudith.com:9092
D, [2017-11-15T13:25:23.413874 #68337] DEBUG -- : Waiting for response 2 from development-magicbus2.cloudith.com:9092
D, [2017-11-15T13:25:23.458023 #68337] DEBUG -- : Received response 2 from development-magicbus2.cloudith.com:9092
E, [2017-11-15T13:25:23.458406 #68337] ERROR -- : Consumer thread crashed: Kafka::GroupAuthorizationCode: Kafka::GroupAuthorizationCode
.rvm/gems/ruby-2.3.1@tms/gems/ruby-kafka-0.4.1/lib/kafka/protocol.rb:96:in `handle_error'
.rvm/gems/ruby-2.3.1@tms/gems/ruby-kafka-0.4.1/lib/kafka/cluster.rb:93:in `block in get_group_coordinator'
.rvm/gems/ruby-2.3.1@tms/gems/ruby-kafka-0.4.1/lib/kafka/cluster.rb:88:in `each'
.rvm/gems/ruby-2.3.1@tms/gems/ruby-kafka-0.4.1/lib/kafka/cluster.rb:88:in `get_group_coordinator'
.rvm/gems/ruby-2.3.1@tms/gems/ruby-kafka-0.4.1/lib/kafka/consumer_group.rb:167:in `coordinator'
.rvm/gems/ruby-2.3.1@tms/gems/ruby-kafka-0.4.1/lib/kafka/consumer_group.rb:111:in `join_group'
.rvm/gems/ruby-2.3.1@tms/gems/ruby-kafka-0.4.1/lib/kafka/consumer_group.rb:40:in `join'
.rvm/gems/ruby-2.3.1@tms/gems/ruby-kafka-0.4.1/lib/kafka/consumer.rb:357:in `join_group'
.rvm/gems/ruby-2.3.1@tms/gems/ruby-kafka-0.4.1/lib/kafka/consumer.rb:374:in `fetch_batches'
.rvm/gems/ruby-2.3.1@tms/gems/ruby-kafka-0.4.1/lib/kafka/consumer.rb:183:in `block in each_message'
.rvm/gems/ruby-2.3.1@tms/gems/ruby-kafka-0.4.1/lib/kafka/consumer.rb:319:in `consumer_loop'
.rvm/gems/ruby-2.3.1@tms/gems/ruby-kafka-0.4.1/lib/kafka/consumer.rb:182:in `each_message'
.rvm/gems/ruby-2.3.1@tms/bundler/gems/racecar-675f42e46cee/lib/racecar/runner.rb:54:in `run'
.rvm/gems/ruby-2.3.1@tms/bundler/gems/racecar-675f42e46cee/lib/racecar.rb:27:in `run'
.rvm/gems/ruby-2.3.1@tms/bundler/gems/racecar-675f42e46cee/lib/racecar/cli.rb:52:in `main'
.rvm/gems/ruby-2.3.1@tms/bundler/gems/racecar-675f42e46cee/exe/racecar:9:in `<top (required)>'
.rvm/gems/ruby-2.3.1@tms/bin/racecar:23:in `load'
.rvm/gems/ruby-2.3.1@tms/bin/racecar:23:in `<main>'
.rvm/gems/ruby-2.3.1@tms/bin/ruby_executable_hooks:15:in `eval'
.rvm/gems/ruby-2.3.1@tms/bin/ruby_executable_hooks:15:in `<main>'
=> Crashed: Kafka::GroupAuthorizationCode
```

The only difference I have found is that in the two environments where the consumer starts successfully, I do not see this in the output:

 Leaving group `test`

Versions of Kafka:
1.  10.0.1
2.  10.2.1
3.  11.0.0

10.2.1 is the env with the failure.

I have tried changing session_timeout, but no difference.

**Comment by dasch** [comment]
What authentication system are you using?

**Comment by surfdog** [comment]
Auth system is SSL, configured on port 9093.  We have a "playground" topic on 9092 that is meant to be for dev work.

From my local machine to the bus, the following work:

kafkacat -b development-magicbus1.cloudith.com:9092 -L
kafkacat -C -b development-magicbus1.cloudith.com:9092 -t playground

However, using same broker, port and topic, running racecar from local machine fails and I get the error message reported previously.

**Comment by dasch** [comment]
`kafkacat` doesn't set up a consumer group. Can you do

```ruby
kafka = Kafka.new(seed_brokers: ["broker:9092"], logger: Logger.new(STDOUT))
kafka.each_message(topic: "playground") {|message| puts message }
```

?

**Comment by dasch** [comment]
Sounds like you've got something like this configured on the brokers: https://docs.confluent.io/current/kafka/authorization.html

Your client may not be authorized to create consumer groups.

**Comment by surfdog** [comment]
I could run the example code.  I suspect you are right about the create consumer group.  I will investigate further.  Thank you.
